# Generated by Django 3.1.14 on 2022-08-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20220820_1308'),
        ('pokemon_entities', '0007_pokemon_evolves_from'),
    ]

    operations = [
    ]
