# Generated by Django 3.1.14 on 2022-08-23 14:33

from django.db import migrations


def change_none_to_empty_str(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    Pokemon.objects.filter(japanese_name__isnull=True).update(japanese_name='')
    Pokemon.objects.filter(english_name__isnull=True).update(english_name='')
    Pokemon.objects.filter(description__isnull=True).update(description='')


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20220820_1455'),
    ]

    operations = [
        migrations.RunPython(change_none_to_empty_str),
    ]
